name: migrantconnectapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  magic_sdk: ^6.0.1
  image_picker: ^1.1.2
  http: ^1.4.0
  shared_preferences: ^2.5.3
  webview_flutter: ^4.9.0 
  go_router: ^16.0.0
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  url_launcher: ^6.3.2
  
  html: ^0.15.4
  intl: ^0.20.2
  supabase_flutter: ^2.9.1
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: Monoton
      fonts:
        - asset: assets/fonts/Monoton-Regular.ttf